AWSTemplateFormatVersion: '2010-09-09'
Description: ''
Parameters: {}
Resources:
  S3Bucket:
  Route53DomainHost:
  CertificateManager:
  CloudfrontDistribution:
  Route53DistributionDomain:
Outputs:
