AWSTemplateFormatVersion: 2010-09-09
Description: 'Personal Template for React Projects'

Parameters:
  Name:
    Description: Name of the React project, will be used for resource names
    Type: String
    Default: project-name

  Environment:
    Type: String
    Default: dev
    Description: Environment name
    AllowedValues:
      - dev
      - test
      - staging
      - prod

  AccountAlias:
    Description: Alias of the AWS account that is currently being deployed to.
    Type: String
    Default: account-name

Mappings:
  Environment:
    dev:
      domain: domain-dev.com
    test:
      domain: domain-test.com
    staging:
      domain: domain-staging.com
    prod:
      domain: domain.com

Resources:

Outputs:
  EKSCluster:
    Description: EKS Cluster hosting React app
    Value: !Ref EKSCluster

  SSLCertificate:
    Description: SSL Certificate for URL
    Value: !Ref SSLCertificate

  CloudfrontDistribution:
    Description: Cloudfront Distribution
    Value: !Ref CloudfrontDistribution

  CloudfrontDomainName:
    Description: URL to access the Cloudfront Distribution
    Value: !GetAtt CloudfrontDistribution.DomainName

  Route53Domain:
    Description: Custom Domain CNAME via Route 53
    Value: !Ref Route53Domain
